'use strict';

const ORDERS = {
    STANDARD_FAST: 'STANDARD_FAST',
    STANDARD_HERO: 'STANDARD_HERO',
    STANDARD_CARNET: 'STANDARD_CARNET',
    EDIT_CARNET: 'EDIT_CARNET',
    EDIT_FAST: 'EDIT_FAST',
    EDIT_HERO: 'EDIT_HERO',
    BUY_CARNET: 'BUY_CARNET',
    CONTEXTUAL_CARNET: 'CONTEXTUAL_CARNET'
}

export default ORDERS;
